### ISSUE TITLE
How can i install this app on my android?

### ISSUE THREAD

**Issue by Eliranl85** [ilmiont/msftbandapp#1]
Hi.
Can you upload an APK file so i can install this app? 
Thanks

**Comment by ilmiont** [comment]
As noted on the repository homepage, this project is no longer in active development by myself.

No prebuilt binaries for any platform are currently available. The functionality of the app is extremely limited and only available for UWP and not Android at this time.

You are welcome to fork the project and continue development yourself. You will need to build for Android yourself if you want to use on your phone.

I have no plans to resume development or provide prebuilt binaries for any platform.
